### PR TITLE
stop ignoring env

### LINKED ISSUE #22: Initial sync logic doesn't take DATA_FOLDER environment variable into account
The logic hardcodes `/data/${foo}` as a path. If you've set the DATA_FOLDER to something else, with the corresponding `volume` mounts, the service crashes with the following backtrace:

```
node:fs:1380
  const result = binding.mkdir(
                         ^

Error: ENOENT: no such file or directory, mkdir '/data/public'
    at Object.mkdirSync (node:fs:1380:26)
    at writeInitialState (/usr/src/build/writeInitialState.js:257:19)
    at /usr/src/build/app.js:48:52
    at new Promise (<anonymous>)
    at Object.<anonymous> (/usr/src/build/app.js:46:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/data/public'
}
```

I've confirmed the following scenarios:
```
    environment:
      DATA_FOLDER: "/ldes/ldes-feed"
    volumes:
      - ./config/ldes-delta-pusher/dispatch.ts:/config/dispatch.ts # our config, probably not relevant
      - ./data/ldes-feed:/ldes/ldes-feed

```
❌ errors

---
```
    volumes:
      - ./config/ldes-delta-pusher/dispatch.ts:/config/dispatch.ts # our config, probably not relevant
      - ./data/ldes-feed:/data

```
✅ works
---
```
    environment:
      DATA_FOLDER: "/ldes/ldes-feed"
    volumes:
      - ./config/ldes-delta-pusher/dispatch.ts:/config/dispatch.ts # our config, probably not relevant
      - ./data/ldes-feed:/ldes/ldes-feed
      - ./data/ldes-feed:/data
```
✅ also works, but perhaps a bit spooky to mount a folder in two places?

### PR DESCRIPTION
**Pull request by Rahien**
Fixes #22

### CODE REVIEW

File: environment.ts [hunk 1]
```diff
@@ -2,11 +2,11 @@ export const LDES_FRAGMENTER = process.env.LDES_FRAGMENTER as
   | string
   | undefined;
 export const LDES_FOLDER = process.env.LDES_FOLDER as string;
-export const DATA_FOLDER = process.env.DATA_FOLDER || "/data" as string;
+export const DATA_FOLDER = process.env.DATA_FOLDER || ("/data" as string);
```
Comment (JonasVanHoof) [inline environment.ts:5]: Should we add a check here to see if it starts with a `/` ?

**Review by JonasVanHoof — COMMENTED** [review]
Code looks good, didn't run it yet

**Review by JonasVanHoof — APPROVED** [review]
Got it working while testing the ldes with OP cc: Karel
